---
_etcd_generate_cert: >-
        {% if (inventory_hostname not in groups['etcd']
        or (inventory_hostname in groups['etcd'] and etcd_action|default('none') in ['create'])
        or etcd_sync_certs | default(false) | bool
        or etcd_rotate_certs | default(false) | bool)
        and not etcd_skip_certs|default(false) | bool %}
        true
        {% else %}
        false
        {% endif %}
