etcd_version: v3.3.10
etcd_download_url: "https://storage.googleapis.com/etcd/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"

etcd_access_addresses_list: |-
  [
  {% for item in groups['etcd'] -%}
    "{{hostvars[item]['etcd_client_url']}}"{% if not loop.last %},{% endif %}
  {%- endfor %}
  ]

etcd_peer_addresses_list: |-
  [
  {% for item in groups['etcd'] -%}
    "{{ hostvars[item]['etcd_name']}}={{ hostvars[item].etcd_peer_url}}"{% if not loop.last %},{% endif %}
  {%- endfor %}
  ]
etcd_access_addresses: "{{etcd_access_addresses_list | join(',')}}"
etcd_access_addresses_semicolon: "{{etcd_access_addresses_list | join(';')}}"

etcd_peer_addresses: "{{etcd_peer_addresses_list | join(',')}}"
etcd_peer_addresses_semicolon: "{{etcd_peer_addresses_list | join(';')}}"

etcd_cert_paths:
      server:
        cert:  "{{ etcd_cert_dir }}/{{ inventory_hostname }}/{{inventory_hostname}}-server.pem"
        key: "{{ etcd_cert_dir }}/{{ inventory_hostname }}/{{inventory_hostname}}-server-key.pem"
        ca: "{{ etcd_cert_dir }}/{{ inventory_hostname }}/client-ca.pem"
      client:
        cert:  "{{ etcd_cert_dir }}/{{ inventory_hostname }}/{{inventory_hostname}}-client.pem"
        key: "{{ etcd_cert_dir }}/{{ inventory_hostname }}/{{inventory_hostname}}-client-key.pem"
        ca: "{{ etcd_cert_dir }}/{{ inventory_hostname }}/client-ca.pem"
      peer:
        cert:  "{{ etcd_cert_dir }}/{{ inventory_hostname }}/{{inventory_hostname}}-peer.pem"
        key: "{{ etcd_cert_dir }}/{{ inventory_hostname }}/{{inventory_hostname}}-peer-key.pem"
        ca: "{{ etcd_cert_dir }}/{{ inventory_hostname }}/peer-ca.pem"
