---
- import_role:
    name: download
  vars:
    downloads: "{{etcd_certs_downloads}}"
    download_container: false
  tags:
    - download
    - etcd-ca
    - etcd-certs

- name: Create etcd certs dir
  file:
    path: "{{ etcd_cert_dir }}"
    group: "{{ etcd_cert_group }}"
    state: directory
    owner: "{{etcd_cert_user}}"
    mode: 0700

- include_tasks: 0010_etcd-ca.yaml
  loop:
    - name: peer
    - name: client
  loop_control:
    loop_var: cert
