---

# Install the etcd cluster
- hosts: etcd
  any_errors_fatal: true
  vars:
    etcd_clusters:
      - name: k8s1
        port:
          client: 2379
          peer: 2380
  roles:
    - name: etcd/cluster

# install the etcd client certificates to all hosts using etcd
# - hosts: etcd-clients
#   roles:
#     - name: etcd/certs/fetch
#       vars:
#         etcd_client_only: true
