---

# Install the etcd cluster
- hosts: etcd
  strategy: linear
  any_errors_fatal: true
  vars:
    etcd_cluster_name: k8s
    etcd_ports:
      client: 2379
      peer: 2380
  tasks:
    - name: Manage etcd cluster
      import_role:
        name: etcd3/cluster
      tags:
        - etcd

# install the etcd client certificates to all hosts using etcd
- hosts: etcd-clients
  strategy: linear
  tasks:
    - name: Create client certificates
      import_role:
        name: etcd3/certs
      tags:
        - etcd-certs
