---

# Install the etcd cluster
- hosts: etcd
  strategy: mitogen_linear
  any_errors_fatal: true
  tasks:
    - name: Manage etcd cluster
      import_role:
        name: etcd3/cluster
      tags:
        - etcd

# install the etcd client certificates to all hosts using etcd
- hosts: etcd-clients
  strategy: mitogen_linear
  tasks:
    - name: Create client certificates
      import_role:
        name: etcd3/certs
      tags:
        - etcd-certs
