---
# Test playbook for download functionality only
# Usage: ansible-playbook -i inventory-test.ini test-download.yaml -b

- name: Test etcd binary downloads
  hosts: etcd
  gather_facts: yes
  tasks:
    - name: Load etcd3 defaults
      include_role:
        name: etcd3
      tags:
        - always

    - name: Download etcd binaries
      include_role:
        name: download_etcd
      vars:
        downloads: "{{ etcd_downloads }}"
      tags:
        - download
        - etcd-download

    - name: Verify etcd archive exists
      stat:
        path: "{{ bin_dir }}/etcd-archive/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
      register: etcd_archive
      tags:
        - verify

    - name: Display etcd download status
      debug:
        msg: "etcd archive downloaded: {{ etcd_archive.stat.exists }}"
      tags:
        - verify

- name: Test cfssl binary downloads
  hosts: etcd-cert-managers
  gather_facts: yes
  tasks:
    - name: Load etcd3 defaults
      include_role:
        name: etcd3
      tags:
        - always

    - name: Download cfssl binaries
      include_role:
        name: download_etcd
      vars:
        downloads: "{{ etcd_certs_downloads }}"
      tags:
        - download
        - cfssl-download

    - name: Verify cfssl binaries exist
      stat:
        path: "{{ bin_dir }}/{{ item }}"
      register: cfssl_bins
      loop:
        - cfssl
        - cfssljson
        - cfssl-certinfo
      tags:
        - verify

    - name: Display cfssl download status
      debug:
        msg: "{{ item.item }}: {{ item.stat.exists }}"
      loop: "{{ cfssl_bins.results }}"
      tags:
        - verify
