---
dependencies:
  - name: etcd

  - name: adduser
    vars:
      user: "{{ etcd_user }}"
    when:
      - not (ansible_os_family in ['CoreOS', 'Container Linux by CoreOS'])

  - name: etcd/facts

  - name: etcd/certs
    tags:
      - etcd-certs

# @TODO(ant31) not in is_atomic
