---
- name: create GCS bucket
  gc_storage:
    bucket: "{{etcd_upload_backup.bucket}}"
    mode: create
    permission: private
    gs_access_key: "{{etcd_upload_backup.access_key}}"
    gs_secret_key: "{{etcd_upload_backup.secret_key}}"
    region: "{{etcd_upload_backup.region|d(omit)}}"
    s3_url: "{{etcd_upload_backup.s3_url|d(omit)}}"
    metadata: "{{etcd_upload_backup.metadata|d(omit)}}"
  when:
    - etcd_upload_backup.storage == "gcs"

- name: create S3 bucket
  s3:
    bucket: "{{etcd_upload_backup.bucket}}"
    mode: create
    permission: private
    access_key: "{{etcd_upload_backup.access_key}}"
    secret_key: "{{etcd_upload_backup.secret_key}}"
    region: "{{etcd_upload_backup.region|d(omit)}}"
    s3_url: "{{etcd_upload_backup.s3_url|d(omit)}}"
    metadata: "{{etcd_upload_backup.metadata|d(omit)}}"
  when:
    - etcd_upload_backup.storage == "s3" or  etcd_upload_backup.storage == "aws"

- name: uploads items
  gc_storage:
    bucket: "{{etcd_upload_backup.bucket}}"
    object: "{{etcd_backup_file | basename}}"
    src: "{{ etcd_backup_file}}"
    mode: put
    permission: private
    gs_access_key: "{{etcd_upload_backup.access_key}}"
    gs_secret_key: "{{etcd_upload_backup.secret_key}}"
    region: "{{etcd_upload_backup.region|d(omit)}}"
  when:
    - etcd_upload_backup.storage == "gcs"

- name: uploads items
  s3:
    bucket: "{{etcd_upload_backup.bucket}}"
    object: "{{etcd_backup_file | basename}}"
    src: "{{ etcd_backup_file}}"
    mode: put
    permission: private
    access_key: "{{etcd_upload_backup.access_key}}"
    secret_key: "{{etcd_upload_backup.secret_key}}"
    region: "{{etcd_upload_backup.region|d(omit)}}"
    s3_url: "{{etcd_upload_backup.s3_url|d(omit)}}"
    metadata: "{{etcd_upload_backup.metadata|d(omit)}}"
  when:
    - etcd_upload_backup.storage == "s3" or  etcd_upload_backup.storage == "aws"
