---
- include_role:
    name: download
  vars:
    downloads: "{{etcd_downloads}}"
    download_container: false

- name: install | Copy etcd and etcdctl binary from download dir
  copy:
    src: "{{ bin_dir }}/etcd/etcd-{{ etcd_version }}-linux-amd64/{{item}}"
    dest: "{{ bin_dir }}/etcd/{{item}}"
    mode: 0755
    remote_src: yes
  with_items:
    - etcd
    - etcdctl

- name: Checksum etcd binary
  stat:
    path: "{{ bin_dir }}/etcd/etcd"
    checksum_algorithm: sha256
    get_checksum: yes
  register: etcdbin

- name: set cluster_state
  set_fact:
    cluster_state: '{% if etcd_action == "upgrade" %}existing{% else %}new{% endif %}'
    etcd_binary_sha256: "{{etcdbin.stat.checksum}}"

- name: check if datadir exists
  stat:
    path: "{{ etcd_data_dir }}"
  register: etcd_data

- name: CREATE | fail if it exists
  assert:
    msg: "Etcd data already exists, can't create the new cluster: {{etcd_cluster_name}}"
    that: not etcd_data.stat.exists
  when:
    - etcd_action == "create"
    - not etcd_force_create |default(false) | bool

- name: UPDATE | fail if not data dir exists
  assert:
    msg: "Etcd data don't exist, can't upgrade the cluster: {{etcd_cluster_name}}"
    that: etcd_data.stat.exists
  when:
    - etcd_action == "upgrade"

- name: CREATE | create etcd data dir
  file:
    path: "{{etcd_data_dir}}"
    state: directory
    owner: "{{ etcd_user.name}}"
    group: "{{ etcd_user.name}}"
  when:
    - etcd_action == "create"

# @TODO In which conditions we want to replace the configuration?
- name: ETCD | Create etcd env file
  template:
    src: etcd.env.j2
    dest: "{{etcd_config_dir}}/{{etcd_name}}.env"
    force: "{{etcd_action == 'upgrade' or etcd_force_create |default(false) | bool}}"
    backup: yes
  register: envchanged

- name: ETCD | Create etcd config file
  template:
    src: etcd-conf.yaml.j2
    dest: "{{etcd_config_dir}}/{{etcd_name}}-conf.yaml"
    force: "{{etcd_action == 'upgrade' or etcd_force_create |default(false) | bool}}"
    backup: yes
  register: confchanged

- name: ETCD | Copy etcd.service systemd file
  template:
    src: "etcd-host.service.j2"
    dest: /etc/systemd/system/{{etcd_name}}.service
    force: "{{etcd_action == 'upgrade' or etcd_force_create |default(false) | bool}}"
    backup: false
  register: etcdsystemd

- name: UPDATE | reload systemd
  command: systemctl daemon-reload
  when:
    - etcd_action == 'upgrade' or etcd_force_create |default(false) | bool
    - etcdsystemd is changed

- name: CREATE | Ensure etcd is running
  delay: 10
  retries: 5
  until: started_etcd is succeeded
  register: started_etcd
  service:
    name: "{{etcd_name}}"
    state: started
    enabled: yes
  when:
    - etcd_action == 'create'


# The delegation and loop, is a workaround to restart 1 by 1 services(serial=1)
- name: UPDATE | Restart etcd
  delay: 20
  retries: 5
  until: restarted_etcd is succeeded
  register: restarted_etcd
  service:
    name: "{{hostvars[item].etcd_name}}"
    state: restarted
    enabled: yes
  run_once: true
  delegate_to: "{{hostvars[item].ansible_ssh_host}}"
  loop:  "{{groups['etcd']}}"
  when:
    - etcd_action == 'upgrade'
    - confchanged is changed or envchanged is changed or etcdsystemd is changed

- name: ETCD | Check if etcd cluster is healthy
  command: >-
    {{ bin_dir }}/etcdctl --endpoints={{ etcd_access_addresses }}
    --cert={{etcd_cert_paths.client.cert}}
    --cacert={{etcd_cert_paths.client.ca}}
    --key={{etcd_cert_paths.client.key}}
    endpoint health
  register: etcd_cluster_is_healthy
  changed_when: false
  retries: 4
  delay: "{{ retry_stagger | default(5)}}"
  until: etcd_cluster_is_healthy.rc == 0
  environment:
    ETCDCTL_API: "3"

- name: set cluster_state to existing
  set_fact:
    cluster_state: existing

- name: CREATE |  etcd as exsiting cluster
  template:
    src: etcd-conf.yaml.j2
    dest: "{{etcd_config_dir}}/{{etcd_name}}-conf.yaml"
    force: yes
    backup: yes
  when:
    - etcd_action == 'create'
