---
- name: Etcd general fact
  set_fact:
    etcd_members: >-
      {%- set _d = {} -%}
      {%- if not etcd_external_provisioner|d(false) -%}
      {%- for host in groups[etcd_cluster_group] -%}
      {%- set node_name = hostvars[host]['etcd_member_name']|default(['etcd', etcd_cluster_name, hostvars[host]['etcd_member_index']|d(loop.index)|string] | join('-')) -%}
      {%- set etcd_address = hostvars[host][ipvar|d("ip")] | default(hostvars[host]['ansible_default_ipv4']['address']) -%}
      {%- set etcd_access_address = hostvars[host].access_ip | default(etcd_address) -%}
      {%- set _member = {
      host: {
        "etcd_member_index": hostvars[host]['etcd_member_index']|d(loop.index)|string,
        "etcd_name": node_name,
        "etcd_address": etcd_address,
        "etcd_access_address": etcd_access_address,
        "etcd_peer_url": "https://" + etcd_access_address + ":" + etcd_ports['peer']|string,
        "etcd_client_url": "https://" + etcd_access_address +":" + etcd_ports['client']|string,
        "etcd_data_dir": etcd_home + "/" + node_name,
        }} -%}
        {%- set _tmp = _d.update(_member) -%}
        {%- endfor -%}
        {%- endif -%}
        {{ _d }}
  tags:
    - facts

- name: Etcd general fact2
  set_fact:
    etcd_clusters: >-
      {%- set _cluster_info = {} -%}
      {%- set _etcd_access_addresses_list = etcd_access_addresses_list|d([]) -%}
      {%- set _etcd_peer_addresses_list = etcd_peer_addresses_list|d([]) -%}
      {%- for host,item in etcd_members.items()  -%}
      {%- set _tmp = _etcd_access_addresses_list.append(item.etcd_client_url) -%}
      {%- set _tmp = _etcd_peer_addresses_list.append(item.etcd_name + '=' + item.etcd_peer_url) -%}
      {%- if inventory_hostname in groups[etcd_cluster_group] and host == inventory_hostname -%}
      {%-   set _tmp = _cluster_info.update(item) -%}
      {%- endif -%}
      {%- endfor -%}

      {%- set _tmp =  _cluster_info.update({
      'cluster': {
      'etcd_cluster_name': etcd_cluster_name,
      'etcd_ports': etcd_ports},
      'etcd_members': etcd_members,
      'etcd_cert_dir': etcd_cert_dir,
      'etcd_access_addresses': _etcd_access_addresses_list | join(','),
      'etcd_access_addresses_semicolon': _etcd_access_addresses_list | join(';'),
      'etcd_peer_addresses': _etcd_peer_addresses_list | join(','),
      'etcd_peer_addresses_semicolon': _etcd_peer_addresses_list | join(';')
      }) -%}
      {%- set _d = {etcd_cluster_name: _cluster_info} -%}
      {{_d}}
  tags:
    - facts

- name: Etcd top-level
  set_fact:
    "{{item.key}}_{{etcd_cluster_name|replace('-','_')}}": "{{item.value}}"
    "{{item.key}}": "{{item.value}}"
  tags:
    - facts
  loop: "{{etcd_clusters[etcd_cluster_name] | dict2items}}"
