---

- name: Etcd general fact
  set_fact:
    etcd_cluster_{{item.name|replace("-", "_")}}:
       etcd_ports: "{{item.ports}}"
       etcd_cluster_name: "{{item.name}}"
       etcd_members: >-
          {%- set _d = {} -%}
          {%- if not etcd_external_provisioner|d(false) -%}
          {%- for host in groups['etcd'] -%}
          {%- set node_name = hostvars[host]['etcd_member_name']|default(['etcd', item.name, loop.index|string] | join('-')) -%}
          {%- set etcd_address = hostvars[host].ip | default(hostvars[host]['ansible_default_ipv4']['address']) -%}
          {%- set etcd_access_address = hostvars[host].access_ip | default(etcd_address) -%}
          {%- set _member = {
            host: {
            "etcd_member_index": loop.index|string,
            "etcd_name": node_name,
            "etcd_address": etcd_address,
            "etcd_access_address": etcd_access_address,
            "etcd_peer_url": "https://" + etcd_access_address + ":" + item.ports['peer']|string,
            "etcd_client_url": "https://" + etcd_access_address +":" + item.ports['client']|string,
            "etcd_data_dir": etcd_home + "/" + node_name,
            "etcd_backup_dir": etcd_home + "/backups/" + node_name,
            "etcd_backup_prefix": etcd_home + "/backups/" + node_name + "/" + node_name
            }} -%}
          {%- set _tmp = _d.update(_member) -%}
          {%- endfor -%}
          {%- endif -%}
          {{ _d }}

  loop: "{{etcd_clusters}}"
  tags:
    - facts

- name: Etcd general fact
  set_fact:
    etcd_clusters_facts: >-
      {%- set _d = {} -%}
      {%- for cluster in etcd_clusters -%}
      {%- set _members = hostvars[inventory_hostname]['etcd_cluster_' + cluster.name|replace("-", "_")] -%}
      {%- set _etcd_access_addresses_list = cluster.etcd_access_addresses_list|d([]) -%}
      {%- set _etcd_peer_addresses_list = cluster.etcd_peer_addresses_list|d([]) -%}
      {%- for host,item in _members.etcd_members.items()  -%}
      {%- set _tmp = _etcd_access_addresses_list.append(item.etcd_client_url) -%}
      {%- set _tmp = _etcd_peer_addresses_list.append(item.etcd_name + "=" + item.etcd_peer_url) -%}
      {%- endfor -%}

      {%- set _cluster_info = {
      "etcd_ports": cluster.ports,
      "etcd_cluster_name": cluster.name,
      "etcd_access_addresses": _etcd_access_addresses_list | join(','),
      "etcd_access_addresses_semicolon": _etcd_access_addresses_list | join(';'),
      "etcd_peer_addresses": _etcd_peer_addresses_list | join(','),
      "etcd_peer_addresses_semicolon": _etcd_peer_addresses_list | join(';')
      } -%}
      {%- set _tmp = _cluster_info.update(_members) -%}
      {%- set _tmp = _d.update({cluster.name: _cluster_info }) -%}
      {%- endfor -%}
      {{ _d }}
  tags:
    - facts

- debug:
    msg: "{{etcd_clusters_facts}}"
