---
- name: etcd3/backups
  include_role:
    name: etcd3/backups
    public: yes
    apply:
      tags:
        - etcd-backups
  when:
    - inventory_hostname == groups['etcd'][0]
    - etcd_action | default('none') == "backup"
  tags:
    - etcd-backups

# Teardown a cluster
- name: etcd3/cluster/delete
  include_role:
    name: etcd3/cluster/delete
    public: yes
    apply:
      tags:
        - etcd-delete
  when:
    - etcd_delete_cluster | default(false) | bool
  tags:
    - etcd-delete

# Install or upgrade cluster
- name: etcd3/cluster/install
  include_role:
    name: etcd3/cluster/install
    public: yes
    apply:
      tags:
        - etcd
        - etcd-cluster
  when:
    - etcd_action | default('none') in ['upgrade', 'create']
  tags:
    - etcd
    - etcd-cluster
