---
dependencies:
  - name: etcd3
    tags:
      - always

  # Teardown a cluster
  - name: etcd3/cluster/delete
    when:
      - etcd_delete_cluster | default(false) | bool
    tags:
      - etcd-delete

  # Install or upgrade cluster
  - name: etcd3/cluster/install
    when:
      - etcd_action | default('none') in ['upgrade', 'create']
    tags:
      - etcd
      - etcd-cluster
