---

- name: fact1
  set_fact:
    etcd_member_index: |-
      {% for host in groups['etcd']  %}
      {% if inventory_hostname == host %}{{loop.index|string}}{% endif %}
      {% endfor %}
    etcd_address: "{{ip | default(ansible_default_ipv4['address'])}}"
    etcd_access_address: "{{ access_ip | default(ip | default(ansible_default_ipv4['address'])) }}"
    tags:
      - facts

- name: fact2
  set_fact:
    etcd_name: "{{cluster_name + '-' + etcd_member_name|default('etcd' + '-' + etcd_member_index)}}"
    etcd_peer_url: "https://{{ etcd_access_address }}:{{etcd_ports['peer']}}"
    etcd_client_url: "https://{{ etcd_access_address }}:{{etcd_ports['client']}}"
  tags:
    - facts


